namespace NxtRemote;

public enum NxtCommand : byte
    {
        StartProgram = 0x00,
        StopProgram = 0x01,
        PlaySoundFile = 0x02,
        PlayTone = 0x03,
        SetOutputState = 0x04,
        SetInputMode = 0x05,
        GetOutputState = 0x06,
        GetInputValues = 0x07,
        ResetInputScaledValue = 0x08,
        MessageWrite = 0x09,
        ResetMotorPosition = 0x0A,
        GetBatteryLevel = 0x0B,
        StopSoundPlayback = 0x0C,
        KeepAlive = 0x0D,
        LowSpeedGetStatus = 0x0E,
        LowSpeedWrite = 0x0F,
        LowSpeedRead = 0x10,
        GetCurrentProgramName = 0x11,
        MessageRead = 0x13,
        FileOpenRead = 0x80,
        FileOpenWrite = 0x81,
        FileRead = 0x82,
        FileWrite = 0x83,
        FileClose = 0x84,
        FileDelete = 0x85,
        FindFirstFile = 0x86,
        FindNextFile = 0x87,
        GetFirmwareVersion = 0x88,
        FileOpenWriteLinear = 0x89,
        FileOpenReadLinear = 0x8A,
        FileOpenWriteData = 0x8B,
        FileOpenAppendData = 0x8C,
        RequestFirstModule = 0x90,
        RequestNextModule = 0x91,
        CloseModule = 0x92,
        ReadIoMap = 0x94,
        WriteIoMap = 0x95,
        Boot = 0x97,
        SetBrickName = 0x98,
        GetDeviceInfo = 0x9B,
        DeleteUserFlash = 0xA0,
        PollCommandLength = 0xA1,
        PollCommand = 0xA2,
        BluetoothFactoryReset = 0xA4
    }