namespace NxtRemote;

public enum NxtCommandStatus : byte
{
        Success = 0x00,
        PendingCommunicationTransactionInProgress = 0x20,
        SpecifiedMailboxQueueIsEmpty = 0x40,
        NoMoreHandles = 0x81,
        NoSpace = 0x82,
        NoMoreFiles = 0x83,
        EndOfFileExpected = 0x84,
        EndOfFile = 0x85,
        NotALinearFile = 0x86,
        FileNotFound = 0x87,
        HandleAlreadyClosed = 0x88,
        NoLinearSpace = 0x89,
        UndefinedError = 0x8A,
        FileIsBusy = 0x8B,
        NoWriteBuffers = 0x8C,
        AppendNotPossible = 0x8D,
        FileIsFull = 0x8E,
        FileExists = 0x8F,
        ModuleNotFound = 0x90,
        OutOfBoundary = 0x91,
        IllegalFileName = 0x92,
        IllegalHandle = 0x93,
        RequestFailed = 0xBD,
        UnknownCommand = 0xBE,
        InsanePacket = 0xBF,
        DataContainsOutOfRangeValues = 0xC0,
        CommunicationBusError = 0xDD,
        NoFreeMemoryInCommunicationBuffer = 0xDE,
        SpecifiedChannelOrConnectionNotValid = 0xDF,
        SpecifiedChannelOrConnectionNotConfiguredOrBusy = 0xE0,
        NoActiveProgram = 0xEC,
        IllegalSizeSpecified = 0xED,
        IllegalMailboxQueueIdSpecified = 0xEE,
        AttemptedToAccessInvalidFieldOfStructure = 0xEF,
        BadInputOrOutputSpecified = 0xF0,
        InsufficientMemoryAvailable = 0xFB,
        BadArguments = 0xFF
}
